### ISSUE TITLE
Mojolicious 9.31 fixes 

### ISSUE THREAD

**Issue by robrwo** [briandfoy/cpan-security-advisory#105]
See https://metacpan.org/release/SRI/Mojolicious-9.31/changes
> This release contains fixes for security issues, everybody should upgrade!

**Comment by briandfoy** [comment]
I think I've added this in 2a6d45cb28fd988ca0d9484881b65aaa33fba23d although I tagged it with the wrong issue number. If there's something else, we can reopen this issue
