### ISSUE TITLE
Email-Address-XS before v1.05

### ISSUE THREAD

**Issue by robrwo** [briandfoy/cpan-security-advisory#106]
See https://github.com/pali/Email-Address-XS/issues/5

It seems there was a flaw in parsing, that was fixed when upgrading the embedded dopvecot parser.

**Comment by briandfoy** [comment]
I don't see the security aspect of this. Sure, it didn't follow the RFC, but could anyone use that for bad? I don't want to get too far away from security announcements or to become an independent source for security analysis. If it should be a security announcement , perhaps it should be reported somewhere else. Once it is judged to be a valid issue, we can include it here.
