### ISSUE TITLE
Log-Any WithStackTrace proxy 1.712-1.715

### ISSUE THREAD

**Issue by robrwo** [briandfoy/cpan-security-advisory#129]
See the [Changes](https://metacpan.org/dist/Log-Any/changes) file:
> Added a parameter to show stack trace arguments when using the
    WithStackTrace proxy. Since these arguments may contain sensitive
    information, they are now removed by default. 

That seems to be a nominal security issue.

**Comment by briandfoy** [comment]
Thanks,
