### ISSUE TITLE
Plack-Middleware-XSRFBlock can be bypassed when not using signed cookies

### ISSUE THREAD

**Issue by robrwo** [briandfoy/cpan-security-advisory#130]
See https://metacpan.org/dist/Plack-Middleware-XSRFBlock/changes
> Revision history for Plack-Middleware-XSRFBlock
> 
> 0.0.19    2023-07-14 10:17:10+01:00 Europe/London
>  - SECURITY FIX! when *not* using signed cookies, it was possible to
>    bypass XSRFBlock by POSTing an empty form value and an empty cookie

**Comment by briandfoy** [comment]
Thanks,
