### ISSUE TITLE
Possible security fix for CGI-Info

### ISSUE THREAD

**Issue by robrwo** [briandfoy/cpan-security-advisory#164]
The latest release of CGI-Info (0.84) on CPAN mentions a security fix https://github.com/nigelhorne/CGI-Info/commit/374577bdc211529965ee5212180ec3fe1d77c72a

CC @nigelhorne

**Comment by stigtsp** [comment]
At first glance this looks like some WAF type rules for reporting SQLi attacks

**Comment by nigelhorne** [comment]
> At first glance this looks like some WAF type rules for reporting SQLi attacks

It is just that.
