### ISSUE TITLE
CPANSA-DB release metadata broken

### ISSUE THREAD

**Issue by robrwo** [briandfoy/cpan-security-advisory#169]
MetaCPAN reports it as being in RT https://rt.cpan.org/Public/Dist/Display.html?Name=CPANSA-DB

The README gives https://github.com/briandfoy/https://github.com/briandfoy/cpan-security-advisory/issues which I assume is a typo for this repo.

**Comment by briandfoy** [comment]
The READMEs were some global search and replace errors (204fb14f5b920689db59a290d5adb6393d3e29cf)

The metadata had a typo in the URL scheme. (ac4759b50dc871116967cb3542917a98479f3c47)

**Comment by briandfoy** [comment]
Let's see what MetaCPAN does with the new dist. I'll keep this open until I can verify MetaCPAN shows what I expect. Thanks,

**Comment by briandfoy** [comment]
This looks fixed to me in MetaCPAN. If you see that it's not, we can re-open this issue.
