### ISSUE TITLE
Graphics-ColorNames ambiguity between module and file names

### ISSUE THREAD

**Issue by robrwo** [briandfoy/cpan-security-advisory#17]
There is no CVE for this. The RT issue is https://rt.cpan.org/Public/Bug/Display.html?id=54500

This affects versions v2.0_01 through v3.1.2.

Do not report security issues here first! Go to the distribution's maintainers
first and follow their procedures. We only deal with existing reports
and are not a primary source of security reports.

**Comment by briandfoy** [comment]
Wow, this one is from way back, but that's fine!
