### ISSUE TITLE
The CPANSA-DB distribution requires unused Data::Rx for tests

### ISSUE THREAD

**Issue by robrwo** [briandfoy/cpan-security-advisory#172]
The CPAN distribution of the database requires Data::Rx for tests. but nothing is using that.

https://grep.metacpan.org/search?qd=CPANSA-DB&source=metacpan&q=Data%3A%3ARx

**Comment by briandfoy** [comment]
Yes, I just moved that into xt/. Good catch.

**Comment by briandfoy** [comment]
Done, thanks
