### ISSUE TITLE
Valiant 0.002011 Closed potential security issue 

### ISSUE THREAD

**Issue by robrwo** [briandfoy/cpan-security-advisory#175]
Valiant 0.002011
> Closed potential security issue with deeply nested paramters in the DBIC glue code. This was a hack that could let someone create a child record if you were allowing find_by_unique rather than find by primary key.

See https://github.com/jjn1056/Valiant/commit/242348776cc01e736397767f11f86cc4055817c4

@jjn1056

**Comment by briandfoy** [comment]
Thanks. This report will be in the next release
