### ISSUE TITLE
App-genpass

### ISSUE THREAD

**Issue by robrwo** [briandfoy/cpan-security-advisory#178]
App-genpass before v0.2400 generated passwords using build in rand(). Fixed in v0.2400.

See https://metacpan.org/dist/App-Genpass/changes

**Comment by briandfoy** [comment]
I'm leaning toward this not being a security issue, but I might be convinced if this made easy to guess passwords. Probably doesn't hurt to add it though.

Maybe someone else can say more about how this affects security.

**Comment by robrwo** [comment]
I think it depends where the password is used. On the same system that generated the password could be an issue.

It doesn't hurt to include it, and is a nudge for someone using CPAN::Audit to upgrade it or justify why it's not worth upgrading.

**Comment by briandfoy** [comment]
just for the reference: xsawyerx/app-genpass#5
