### ISSUE TITLE
Crypt::Random::Source v0.12 or earlier

### ISSUE THREAD

**Issue by robrwo** [briandfoy/cpan-security-advisory#179]
The [Changes](https://metacpan.org/dist/Crypt-Random-Source/changes) file says:
> 0.13      2018-04-08 01:07:39Z
          - remove rand() fallback, which could be used by get_weak and is not safe
            for cryptographic applications

and the [module documentation](https://metacpan.org/pod/Crypt::Random::Source) says
> In versions prior to 0.13, rand could be used as a result of calling get_weak, or get, if no random device was available. This implies that not explicitly asking for get_strong on a non POSIX operating system (e.g. Win32 without the Win32 backend) could have resulted in non cryptographically random data.

So this should probably be added as a security report.

**Comment by briandfoy** [comment]
Data update on its way to CPAN. Thanks,

**Comment by stigtsp** [comment]
CVE requested

**Comment by briandfoy** [comment]
Just open a new issue when there's a number assigned.
