### ISSUE TITLE
Crypt::Random before v1.51 had unsafe includes

### ISSUE THREAD

**Issue by robrwo** [briandfoy/cpan-security-advisory#182]
See https://metacpan.org/dist/Crypt-Random/changes and RT https://rt.cpan.org/Ticket/Display.html?id=128062

The shebang line in the makerandom script:
```diff
diff --git a/bin/makerandom b/bin/makerandom
index 29b21c6..cfe5485 100755
--- a/bin/makerandom
+++ b/bin/makerandom
@@ -1,4 +1,4 @@
-#!/usr/bin/perl -sI../lib -Ilib/
+#!/usr/bin/perl
 ##
 ## makerandom - interface to crypt::random
 ##
```

**Comment by stigtsp** [comment]
https://github.com/atoomic/Crypt-Random/pull/1

This should also have a CVE, I'll look at that later today
