### ISSUE TITLE
Crypt::Primes  bin/largeprimes has unsafe imports

### ISSUE THREAD

**Issue by robrwo** [briandfoy/cpan-security-advisory#183]
RT https://rt.cpan.org/Ticket/Display.html?id=128058
> bin/largeprimes is using a custom shebang, which force to load modules from several locations: '..', '../lib', 'lib'
this could lead to load modules from an unpredictable location depending from where the script is run and what user is running it.

See also See #182. 

This issue has been public since 2018 but has not yet been fixed.

**Comment by stigtsp** [comment]
https://github.com/atoomic/Crypt-Primes/pull/2

Should also have a CVE

**Comment by briandfoy** [comment]
Added, thanks.
