### ISSUE TITLE
Break out CPAN::Audit::DB

### ISSUE THREAD

**Issue by briandfoy** [briandfoy/cpan-security-advisory#31]
I'm making several release but the only thing that's changing is the generated module. Instead of updating the entire distribution (and bumping the version of CPAN::Audit each time), there could be a separate distro with just the database.

**Comment by robrwo** [comment]
That makes sense.

**Comment by briandfoy** [comment]
There's now a poll: https://github.com/briandfoy/cpan-audit/discussions/7

**Comment by briandfoy** [comment]
This was done this month with the separate distribution of CPAN::Audit::DB and the new CPANSA::DB, which are the same stuff in different namespaces. Eventually CPAN::Audit::DB will disappear.
