### ISSUE TITLE
Catalyst-Action-REST security issue?

### ISSUE THREAD

**Issue by robrwo** [briandfoy/cpan-security-advisory#32]
See https://metacpan.org/dist/Catalyst-Action-REST/changes

Version 1.12 removed YAML from the default mapping. I believe this was in part due to security issues, since you could instantiate an arbitrary Perl object.

Should pre-1.12

**Comment by briandfoy** [comment]
I think this is the same as the [Ruby Christmas Bug](https://www.kalzumeus.com/2013/01/31/what-the-rails-security-issue-means-for-your-startup/).

What I don't know is if this module fixed this. It removed some deps, I guess, but you can re-enable them.
