### ISSUE TITLE
Term-ReadLine-Gnu security issue or not?

### ISSUE THREAD

**Issue by robrwo** [briandfoy/cpan-security-advisory#37]
I added a CVE-issue for [Term-ReadLine-Gnu](https://metacpan.org/pod/Term::ReadLine::Gnu) at 1067c02f2f7b61bbd2aceda89cff0c84a8d06c42 but then reverted it, since the distribution does not actually embed the readline library. It just uses the system one.

However, older versions will use an older system readline library, which might be insecure. I'm on the fence about this, since it could be a sign that the system may have an issue. I am wondering if instead we have a key in the metadata to suggest a possible issue with a related library.

**Comment by robrwo** [comment]
Possibly a separate tag from "embedded_vulnerability", called "external_vulnerability" that is used to indicate a vulnerability associated with a link to en external library?

**Comment by briandfoy** [comment]
> Possibly a separate tag from "embedded_vulnerability", called "external_vulnerability" that is used to indicate a vulnerability associated with a link to en external library?

Now that's getting a bit tricky. I would combine those into one thing:

```
external_vunerability: ...
   name: ...
   affected_versions: ...
   embedded: {true|false}
   ...
```
