### ISSUE TITLE
Move some of information from README to CONTRIBUTING

### ISSUE THREAD

**Issue by robrwo** [briandfoy/cpan-security-advisory#43]
Some of the information in the README file belongs on CONTRIBUTING

**Comment by robrwo** [comment]
I'm thinking the technical details in the README are a bit much. The README should contain an introduction and link to other documents.

We might want to write some POD or Markdown and split this information out into multiple documents:
- README as simple intro that links to other documents
- CONTRIBUTING with how to contribute
- Another document about the format of the YAML files

The CONTRIBUTING document also outline how I have been researching other security issues
- Reading through changelogs, and possibly running diffs
- Searching CPAN for files (e.g. `zlib.h`) that may be embedded libraries

I guess I should start writing something about that.

**Comment by robrwo** [comment]
Edit: we should have a FAQ as well, especially for module authors
1. reporting a security issue
2. reporting a resolved security issue
3. disputing a security issue
4. upstream issues

As for 4, one common issue is that embedded dependencies may have an older version of a library that they have embedded, e.g. zlib in libgit2. These are issues that may require upstream fixes.

**Comment by briandfoy** [comment]
If you want to start a FAQ, let's put that into the wiki. Do the same for the particular way you are doing things and link to them. You should be able to do make wiki pages.

I like the README as the QuickStart sort of document, though. It does seem nice to organize information minutely, but people tend not to find it. 

But, with our limited time, I think we should focus on the data right now. We aren't exactly drowning in requests in how to participate at the moment :)
