### ISSUE TITLE
Many distributions include jQuery

### ISSUE THREAD

**Issue by robrwo** [briandfoy/cpan-security-advisory#45]
See #44 but a search on metacpan for "jquery" returns many distributions that may include a version of jQuery or use hardcoded links for older versions of jQuery and related tools, such as jQuery-mobile

For example, Resource-Pack-jQuery-0.01 has jQuery-1.4.2

**Comment by briandfoy** [comment]
I'm starting to think that we might attack this from another angle. 

First, eventually we need to go relational. I think SQLite is going to solve some of these problems. It will create other problems, too. Our NoSQL approach is going to eventually overwhelm us.

Perhaps one idea is to keep a separate list of modules that have external or embedded libraries, then track vulnerabilities in those libraries too. So, we'd have a file like `cpanas/external/Resource-Pack-jQuery` that looked like:

```
- version: 1.2
   libraries:
     - name: jQuery
        version: v5.6.7
```

Then, some other file more like what we have already, but for these libraries

```
- affected_versions: ...
   fixed_versions: ...
   cves: [ ... ]
```

The processing then has to do the JOIN between those two. This is obviously easier in a relational solution. 

In the mean time, maybe you can have a `references` sort of record in the CPANSA file so you don't copy the same stuff everywhere:

```
- references: externals/jquery-1.4.2.yml
```

I've looked at various solutions to include a YAML file in another file and didn't find a satisfying solution. I think some tools can do it. I don't know if a Perl YAML tool will do it.

**Comment by robrwo** [comment]
I'm starting to think this is getting complicated and repetitive.

I think we need the following "tables"
- CVEs and other security issues
- A list of CPAN distributions tracking to the security issues
- A list of external libraries tracking security issues (possibly sharing same table as CPAN distros)
- A list of CPAN distributions tracking dependencies

I've heard about recutils and am curious, as it allows one to create text files that can be queried like a database. This had the advantage that the data can be kept in a git repo.

**Comment by briandfoy** [comment]
For now, just collect the data the best you can in any form. We can always organize it better later. If this means that we don't immediately make the current-style YAML files, that's fine. It's better to have the info in a less perfect form than to not have it at all.

**Comment by robrwo** [comment]
I'm closing this as a duplicate of #44
