### ISSUE TITLE
The make_record utility needs some improvements

### ISSUE THREAD

**Issue by robrwo** [briandfoy/cpan-security-advisory#48]
Some suggestions for improving the utility.  
- [x] It should format the description to make yamllint happy

It should support command-line options to
- [x] create or append to the file
- [x] specify affected/resolved versions
- [x] specify embedded library
- [x] take an RT number to append to top of references

**Comment by briandfoy** [comment]
These are good ideas.

**Comment by briandfoy** [comment]
Folded description handled in 35b63201d436cb882717ded7d35f37ad0f7daebb
