### ISSUE TITLE
Should we add metadata flags to indicate compiled binaries are included with a distribution?

### ISSUE THREAD

**Issue by robrwo** [briandfoy/cpan-security-advisory#53]
The Tcl module seems to include compiled binaries in https://metacpan.org/release/VKON/Tcl-1.27/source/tcl-core

I've run across modules that have .jar and .class files.

Some Win32 modules have .lib files.

**Comment by briandfoy** [comment]
I think we should, I just don't how the best way yet. In the embedded_vulnerability object, just add a `compiled` key for now. We can change that later if we have a better idea.
